name: music-parser
channels:
  - defaults
dependencies:
  - pip
  - python=3.11.11
  - pip:
      - spotipy==2.24.0
      - python-telegram-bot[webhooks]==21.9 # reference: https://github.com/python-telegram-bot/python-telegram-bot?tab=readme-ov-file#optional-dependencies
      - yt-dlp==2024.12.23
  #     - youtube-dl
