# Schema documented at https://render.com/docs/yaml-spec
services:
  - type: web # valid values: https://render.com/docs/yaml-spec#type
    name: media-parser-bot
    # env: docker # valid values: https://render.com/docs/yaml-spec#environment
    plan: free # optional; defaults to starter
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    # numInstances: 0
